### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by renhehehe** [openvla/openvla#124]
when i run this code 
`import tensorflow_datasets as tfds
ds = tfds.load("bridge_orig", data_dir="/home/sevnce/rh/all_data_in_this_file/dataset", split="train")`

i got erro like this:
`2024-09-25 17:27:59.422605: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-25 17:27:59.422680: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-25 17:27:59.424266: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-25 17:27:59.432417: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-25 17:28:00.450729: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-09-25 17:28:03.009689: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 838 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:23:02.0, compute capability: 8.6
2024-09-25 17:28:03.011838: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 904 MB memory:  -> device: 1, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:24:00.0, compute capability: 8.6
2024-09-25 17:28:03.013726: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 904 MB memory:  -> device: 2, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:24:01.0, compute capability: 8.6
2024-09-25 17:28:03.015483: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 904 MB memory:  -> device: 3, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:24:02.0, compute capability: 8.6
2024-09-25 17:28:03.017245: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /job:localhost/replica:0/task:0/device:GPU:4 with 22225 MB memory:  -> device: 4, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:24:03.0, compute capability: 8.6
2024-09-25 17:28:03.019121: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /job:localhost/replica:0/task:0/device:GPU:5 with 22225 MB memory:  -> device: 5, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:24:04.0, compute capability: 8.6
Exception ignored in: <function AtomicFunction.__del__ at 0x7f6a9d3130a0>
Traceback (most recent call last):
  File "/home/sevnce/.conda/envs/openvla_rh/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function AtomicFunction.__del__ at 0x7f6a9d3130a0>
Traceback (most recent call last):
  File "/home/sevnce/.conda/envs/openvla_rh/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable`

my_dataset use brigedatav2:
![image](https://github.com/user-attachments/assets/e243fd54-8b7f-4614-969d-f41ab2d5759d)

**Comment by renhehehe** [comment]
I solved this problem by upgrading TensorFlow version to 2.17.0，this issues will be closed
