### ISSUE TITLE
AttributeError about 'module'

### ISSUE THREAD

**Issue by Vincentlu1412** [openvla/openvla#130]
thanks for your work! BUT facing AttributeError as shown below:
re absl::InitializeLog() is called are written to STDERR
W0000 00:00:1728100309.419724   29683 op_level_cost_estimator.cc:699] Error in PredictCost() for the op: op: "CropAndResize" attr { key: "T" value { type: DT_FLOAT } } attr { key: "extrapolation_value" value { f: 0 } } attr { key: "method" value { s: "bilinear" } } inputs { dtype: DT_FLOAT shape { dim { size: 1 } dim { size: 224 } dim { size: 224 } dim { size: -7 } } } inputs { dtype: DT_FLOAT shape { dim { size: -2 } dim { size: 4 } } } inputs { dtype: DT_INT32 shape { dim { size: -2 } } } inputs { dtype: DT_INT32 shape { dim { size: 2 } } } device { type: "CPU" vendor: "GenuineIntel" model: "111" frequency: 2599 num_cores: 48 environment { key: "cpu_instruction_set" value: "AVX SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2" } environment { key: "eigen" value: "3.4.90" } l1_cache_size: 32768 l2_cache_size: 262144 l3_cache_size: 31457280 memory_size: 268435456 } outputs { dtype: DT_FLOAT shape { dim { size: -2 } dim { size: -8 } dim { size: -9 } dim { size: -7 } } }
W0000 00:00:1728100309.420206   29683 op_level_cost_estimator.cc:699] Error in PredictCost() for the op: op: "CropAndResize" attr { key: "T" value { type: DT_FLOAT } } attr { key: "extrapolation_value" value { f: 0 } } attr { key: "method" value { s: "bilinear" } } inputs { dtype: DT_FLOAT shape { dim { size: 1 } dim { size: 224 } dim { size: 224 } dim { size: -6 } } } inputs { dtype: DT_FLOAT shape { dim { size: -3 } dim { size: 4 } } } inputs { dtype: DT_INT32 shape { dim { size: -3 } } } inputs { dtype: DT_INT32 shape { dim { size: 2 } } } device { type: "CPU" vendor: "GenuineIntel" model: "111" frequency: 2599 num_cores: 48 environment { key: "cpu_instruction_set" value: "AVX SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2" } environment { key: "eigen" value: "3.4.90" } l1_cache_size: 32768 l2_cache_size: 262144 l3_cache_size: 31457280 memory_size: 268435456 } outputs { dtype: DT_FLOAT shape { dim { size: -3 } dim { size: -10 } dim { size: -11 } dim { size: -6 } } }
Traceback (most recent call last):                                                                                                                                                  
  File "/home/luwt/anaconda3/envs/openvla/lib/python3.10/site-packages/peft/peft_model.py", line 619, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/home/luwt/anaconda3/envs/openvla/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'PeftModel' object has no attribute 'module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luwt/anaconda3/envs/openvla/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 330, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/home/luwt/anaconda3/envs/openvla/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'LoraModel' object has no attribute 'module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luwt/openvla/vla-scripts/finetune_ddp.py", line 376, in <module>
    finetune()
  File "/home/luwt/anaconda3/envs/openvla/lib/python3.10/site-packages/draccus/argparsing.py", line 203, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/home/luwt/openvla/vla-scripts/finetune_ddp.py", line 271, in finetune
    action_logits = output.logits[:, vla.module.vision_backbone.featurizer.patch_embed.num_patches : -1]
  File "/home/luwt/anaconda3/envs/openvla/lib/python3.10/site-packages/peft/peft_model.py", line 621, in __getattr__
    return getattr(self.base_model, name)
  File "/home/luwt/anaconda3/envs/openvla/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 332, in __getattr__
    return getattr(self.model, name)
  File "/home/luwt/anaconda3/envs/openvla/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'OpenVLAForActionPrediction' object has no attribute 'module'

**Comment by moojink** [comment]
Hi @Vincentlu1412,

By any chance, did you remove the DDP wrapper? The `.module` is used to access the underlying model object (inside the DDP wrapper), but the stack trace suggests that you already have the unwrapped model object. If so, you can just remove the `.module` in the code.

-Moo Jin
