### ISSUE TITLE
[_pickle.UnpicklingError: invalid load key, 'v'.] When Full Fine-Tuning on LIBERO

### ISSUE THREAD

**Issue by YEOMJINSEOP** [openvla/openvla#151]
Hi, i'm trying to fully fine-tune openvla-7b-prismatic on modified_libero_rlds datasets.

I made training configuration for LIBERO in `openvla/prismatic/conf/vla.py` as below, and registered in `VLA Registry` at the bottom of vla.py.

However, i encounter this error.  Have anyone has an idea for this error??

`
11/05 [05:31:13] INFO     | >>     |=> Loading llama2 (Fast) Tokenizer via the AutoTokenizer API                  base_llm.py:151
Traceback (most recent call last):
  File "/workspace/openvla/vla-scripts/train.py", line 264, in <module>
    train()
  File "/opt/conda/envs/openvla/lib/python3.10/site-packages/draccus/argparsing.py", line 203, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/workspace/openvla/vla-scripts/train.py", line 150, in train
    vlm = load_vla(cfg.pretrained_checkpoint, hf_token=hf_token, load_for_training=True)
  File "/workspace/openvla/prismatic/models/load.py", line 215, in load_vla
    vla = OpenVLA.from_pretrained(
  File "/workspace/openvla/prismatic/models/vlms/prismatic.py", line 108, in from_pretrained
    model_state_dict = torch.load(pretrained_checkpoint, map_location="cpu")["model"]
  File "/opt/conda/envs/openvla/lib/python3.10/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/envs/openvla/lib/python3.10/site-packages/torch/serialization.py", line 1258, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
`

[openvla/prismatic/conf/vla.py]

`
@dataclass
class Exp_DinoSigLIP_224px_Libero_Spatial(VLAConfig):
    vla_id: str = "dinosiglip-224px-libero-spatial"
    base_vlm: Union[str, Path] = "prism-dinosiglip-224px+7b"

    freeze_vision_backbone: bool = False
    freeze_llm_backbone: bool = False
    unfreeze_last_llm_layer: bool = False

    data_mix: str = "libero_spatial_no_noops"
    shuffle_buffer_size: int = 100_000

    # Optimization Parameters
    epochs: int = 6400
    max_steps: Optional[int] = 220

    expected_world_size: int = 4
    global_batch_size: int = 64
    per_device_batch_size: int = 16

    learning_rate: float = 5e-4
    weight_decay: float = 0.0
    max_grad_norm: float = 1.0
    lr_scheduler_type: str = "constant"
    warmup_ratio: float = 0.0

    train_strategy: str = "fsdp-full-shard"
`
`# === Define a VLA Registry Enum for Reference & Validation ===
@unique
class VLARegistry(Enum):
    #######################################################################################
    DINOSIGLIP_224PX_LIBERO = Exp_DinoSigLIP_224px_Libero_Spatial
    #######################################################################################
`

and i use this script for training.

`
torchrun --standalone --nnodes 1 --nproc-per-node 4 vla-scripts/train.py \
--pretrained_checkpoint /workspace/openvla-7b-prismatic/checkpoints/step-295000-epoch-40-loss=0.2200.pt \
--vla.type dinosiglip-224px-libero-spatial \
--data_root_dir /SSD/modified_libero_rlds \
--image_aug True --save_interval 1000 \
--is_resume False
`

**Comment by YEOMJINSEOP** [comment]
You should check if openvla-7b-prismatic checkpoint has been installed without problem.
I found it causes above error
