### ISSUE TITLE
Structural Pruning for Language_model of OpenVLA

### ISSUE THREAD

**Issue by Elycyx** [openvla/openvla#168]
I was trying to compress the language_model component (Llama2_7b) of OpenVLA with structural pruning (e.g [LLM-Pruner](https://github.com/horseee/LLM-Pruner) ). Because of the characteristics of structural pruning, the model's dimensions of hidden layers are changed, and when I tried to load the modified OpenVLA, some errors occur like below:
```
Loading checkpoint shards:   0%|                                                                                      | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/jt/cyx/openvla/call.py", line 14, in <module>
    loaded_vla = AutoModelForVision2Seq.from_pretrained(
  File "/home/jt/miniconda3/envs/openvla/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 559, in from_pretrained
    return model_class.from_pretrained(
  File "/home/jt/miniconda3/envs/openvla/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4225, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/jt/miniconda3/envs/openvla/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4728, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/jt/miniconda3/envs/openvla/lib/python3.10/site-packages/transformers/modeling_utils.py", line 993, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/home/jt/miniconda3/envs/openvla/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 286, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([4096, 8256]) in "weight" (which has shape torch.Size([4096, 11008])), this looks incorrect.
```
Any better way for pruning the language_model of OpenVLA and utilize the modified model correctly?

**Comment by kpertsch** [comment]
Hi -- we haven't looked into pruning the model, and can unfortunately not provide a lot of guidance on this topic.
If you want to just run the model on a smaller GPU, we provide some instructions for how to run quantized inference with the model.
