### ISSUE TITLE
CUDA error: device kernel image is invalid

### ISSUE THREAD

**Issue by HeinzYan** [openvla/openvla#176]
Thanks for your great work! But I have some problems:
### Description
I encountered the following error while running a full fine-tune, here is the full traceback:
```
Traceback (most recent call last):
  File "/home/zhangji/OpenVLA/vla-scripts/train.py", line 265, in <module>
    train()
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/draccus/argparsing.py", line 203, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/home/zhangji/OpenVLA/vla-scripts/train.py", line 229, in train
    train_strategy.run_setup(run_dir=run_dir, n_train_examples=len(vla_dataset))
  File "/home/zhangji/OpenVLA/prismatic/training/strategies/fsdp.py", line 160, in run_setup
    self.vlm = FSDP(
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 477, in __init__
    _auto_wrap(
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/_wrap_utils.py", line 101, in _auto_wrap
    _recursive_wrap(**recursive_wrap_kwargs, **root_kwargs)  # type: ignore[arg-type]
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 543, in _recursive_wrap
    wrapped_child, num_wrapped_params = _recursive_wrap(
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 543, in _recursive_wrap
    wrapped_child, num_wrapped_params = _recursive_wrap(
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 543, in _recursive_wrap
    wrapped_child, num_wrapped_params = _recursive_wrap(
  [Previous line repeated 1 more time]
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 561, in _recursive_wrap
    return _wrap(module, wrapper_cls, **kwargs), nonwrapped_numel
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 490, in _wrap
    return wrapper_cls(module, **kwargs)
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 503, in __init__
    _init_param_handle_from_module(
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/_init_utils.py", line 568, in _init_param_handle_from_module
    _move_module_to_device(
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/_init_utils.py", line 956, in _move_module_to_device
    _move_states_to_device(params_to_move, bufs_to_move, device_from_device_id)
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/_init_utils.py", line 986, in _move_states_to_device
    param.data = param.to(device_from_device_id)
RuntimeError: CUDA error: device kernel image is invalid
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/home/zhangji/OpenVLA/vla-scripts/train.py", line 265, in <module>
    train()
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/draccus/argparsing.py", line 203, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/home/zhangji/OpenVLA/vla-scripts/train.py", line 229, in train
    train_strategy.run_setup(run_dir=run_dir, n_train_examples=len(vla_dataset))
  File "/home/zhangji/OpenVLA/prismatic/training/strategies/fsdp.py", line 160, in run_setup
    self.vlm = FSDP(
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 477, in __init__
    _auto_wrap(
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/_wrap_utils.py", line 101, in _auto_wrap
    _recursive_wrap(**recursive_wrap_kwargs, **root_kwargs)  # type: ignore[arg-type]
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 543, in _recursive_wrap
    wrapped_child, num_wrapped_params = _recursive_wrap(
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 543, in _recursive_wrap
    wrapped_child, num_wrapped_params = _recursive_wrap(
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 543, in _recursive_wrap
    wrapped_child, num_wrapped_params = _recursive_wrap(
  [Previous line repeated 1 more time]
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 561, in _recursive_wrap
    return _wrap(module, wrapper_cls, **kwargs), nonwrapped_numel
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 490, in _wrap
    return wrapper_cls(module, **kwargs)
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 503, in __init__
    _init_param_handle_from_module(
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/_init_utils.py", line 568, in _init_param_handle_from_module
    _move_module_to_device(
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/_init_utils.py", line 956, in _move_module_to_device
    _move_states_to_device(params_to_move, bufs_to_move, device_from_device_id)
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/fsdp/_init_utils.py", line 986, in _move_states_to_device
    param.data = param.to(device_from_device_id)
RuntimeError: CUDA error: device kernel image is invalid
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[2024-12-10 19:55:21,259] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 3445814) of binary: /home/zhangji/miniconda3/envs/openvla/bin/python
Traceback (most recent call last):
  File "/home/zhangji/miniconda3/envs/openvla/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.2.1', 'console_scripts', 'torchrun')())
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zhangji/miniconda3/envs/openvla/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
vla-scripts/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-12-10_19:55:21
  host      : v100-4
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3445815)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-10_19:55:21
  host      : v100-4
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3445814)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```
### Run Command
```
export CUDA_VISIBLE_DEVICES=6,7
export CUDA_LAUNCH_BLOCKING=1
torchrun --standalone --nnodes 1 --nproc-per-node 2 vla-scripts/train.py \
  --pretrained_checkpoint /home/zhangji/OpenVLA/ckpt_full_ft/openvla-7b-prismatic/checkpoints/step-295000-epoch-40-loss=0.2200.pt \
  --vla.type prism-dinosiglip-224px+mx-bridge \
  --data_root_dir /home/longhorn/zhangji/BridgeDataV2 \
  --run_root_dir /home/zhangji/OpenVLA/log \
  --run_id 114514 \
  --image_aug False \
  --wandb_project OpenVLA_full_ft \
  --wandb_entity swjtu \
  --save_interval 500 \
  --is_resume False
```

### Environment Info
As mentioned in [this issue](https://github.com/openvla/openvla/issues/37), I initially thought this might be related to my environment configuration. Therefore, I checked my environment as follows:

**command `nvcc -V` output**
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

**command `cat /proc/driver/nvidia/version` output:**
```
NVRM version: NVIDIA UNIX x86_64 Kernel Module  515.65.01  Wed Jul 20 14:00:58 UTC 2022
GCC version:  gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2)
```

**command `nvidia-smi` output:**
```
Tue Dec 10 20:51:29 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:06:00.0 Off |                  Off |
| N/A   37C    P0    41W / 300W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:07:00.0 Off |                  Off |
| N/A   38C    P0    43W / 300W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:0A:00.0 Off |                  Off |
| N/A   37C    P0    42W / 300W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:0B:00.0 Off |                  Off |
| N/A   36C    P0    43W / 300W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM2...  On   | 00000000:85:00.0 Off |                  Off |
| N/A   38C    P0    41W / 300W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-SXM2...  On   | 00000000:86:00.0 Off |                  Off |
| N/A   37C    P0    43W / 300W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  Tesla V100-SXM2...  On   | 00000000:89:00.0 Off |                  Off |
| N/A   39C    P0    42W / 300W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  Tesla V100-SXM2...  On   | 00000000:8A:00.0 Off |                  Off |
| N/A   36C    P0    43W / 300W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

**PyTorch version:**
```
torch                     2.5.0+cu118              pypi_0    pypi
torchaudio                2.5.0+cu118              pypi_0    pypi
torchtriton               2.2.0                     py310    pytorch
torchvision               0.20.0+cu118             pypi_0    pypi
```

**Command `torch.cuda.is_available()` output:**
```
(openvla) zhangji@v100-4:~/OpenVLA$ python -c "import torch; print(torch.cuda.is_available()); print(torch.cuda.device_count())"
True
2
```

Additionally, to further confirm whether my environment can effectively utilize FSDP (as mentioned in [this issue](https://github.com/openvla/openvla/issues/37)), I ran the following code using `torchrun --nproc_per_node=2 cuda_test.py`:
```
import os
import torch
import torch.nn as nn
import torch.optim as optim
from torch.distributed import init_process_group
from torch.distributed.fsdp import FullyShardedDataParallel as FSDP

def main():
    init_process_group(backend='nccl')
    local_rank = int(os.environ['LOCAL_RANK'])
    torch.cuda.set_device(local_rank)
    device = torch.device('cuda', local_rank)

    model = nn.Sequential(
        nn.Linear(10, 10),
        nn.ReLU(),
        nn.Linear(10, 5)
    ).to(device)

    fsdp_model = FSDP(model)

    criterion = nn.MSELoss()
    optimizer = optim.Adam(fsdp_model.parameters(), lr=0.001)

    input = torch.randn(20, 10).to(device)
    target = torch.randn(20, 5).to(device)

    output = fsdp_model(input)
    loss = criterion(output, target)
    loss.backward()
    optimizer.step()
    print(f"Rank {local_rank} finished.")
    torch.distributed.destroy_process_group()

if __name__ == "__main__":
    main()
```
Execution Result:
```
(openvla) zhangji@v100-4:~/OpenVLA$ torchrun --nproc_per_node=2 cuda_test.py
Rank 1 finished.
Rank 0 finished.
```
As per [this comment](https://github.com/openvla/openvla/issues/37#issuecomment-2242551253), I recreated a new conda environment and reran the full fine-tune command, but still encountered the same issue.

### Additional Information
Operating System: Ubuntu 20.04.6 LTS
CUDA Installation Path: /home/zhangji/cuda-11.8 (I don't have administrative rights; CUDA is installed in my user directory)
Running result of `/home/zhangji/cuda-11.8/extras/demo_suite/deviceQuery`:
```
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 2 CUDA Capable device(s)

Device 0: "Tesla V100-SXM2-32GB"
  CUDA Driver Version / Runtime Version          11.7 / 11.8
  CUDA Capability Major/Minor version number:    7.0
  Total amount of global memory:                 32511 MBytes (34089926656 bytes)
  (80) Multiprocessors, ( 64) CUDA Cores/MP:     5120 CUDA Cores
  GPU Max Clock rate:                            1530 MHz (1.53 GHz)
  Memory Clock rate:                             877 Mhz
  Memory Bus Width:                              4096-bit
  L2 Cache Size:                                 6291456 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 6 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 137 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

Device 1: "Tesla V100-SXM2-32GB"
  CUDA Driver Version / Runtime Version          11.7 / 11.8
  CUDA Capability Major/Minor version number:    7.0
  Total amount of global memory:                 32511 MBytes (34089926656 bytes)
  (80) Multiprocessors, ( 64) CUDA Cores/MP:     5120 CUDA Cores
  GPU Max Clock rate:                            1530 MHz (1.53 GHz)
  Memory Clock rate:                             877 Mhz
  Memory Bus Width:                              4096-bit
  L2 Cache Size:                                 6291456 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 6 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 138 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
> Peer access from Tesla V100-SXM2-32GB (GPU0) -> Tesla V100-SXM2-32GB (GPU1) : Yes
> Peer access from Tesla V100-SXM2-32GB (GPU1) -> Tesla V100-SXM2-32GB (GPU0) : Yes

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 11.7, CUDA Runtime Version = 11.8, NumDevs = 2, Device0 = Tesla V100-SXM2-32GB, Device1 = Tesla V100-SXM2-32GB
Result = PASS
```

How can I resolve this issue? Thank you for your assistance! :3

**Comment by LemonZhong** [comment]
Same problem here

**Comment by LemonZhong** [comment]
My cuda version and pytorch version don't have any conflict. But still have this problem
