### ISSUE TITLE
torch.distributed.DistNetworkError: Connection reset by peer

### ISSUE THREAD

**Issue by object814** [openvla/openvla#61]
Hi I am encountering this error while runing LoRA finetuning:
`CUDA_VISIBLE_DEVICES=0,1,2,3,4,5 torchrun --standalone --nnodes 1 --nproc-per-node 6 vla-scripts/finetune.py`
I searched all over the internet and still cannot solve this error:

Traceback (most recent call last):
  File "/data/zhouhy/VLA-Continual-Learning/external/openvla/vla-scripts/seq_finetune.py", line 52, in <module>
    from prismatic.models.backbones.llm.prompting import PurePromptBuilder, VicunaV15ChatPromptBuilder
  File "/data/zhouhy/VLA-Continual-Learning/external/openvla/prismatic/__init__.py", line 1, in <module>
    from .models import available_model_names, available_models, get_model_description, load
  File "/data/zhouhy/VLA-Continual-Learning/external/openvla/prismatic/models/__init__.py", line 1, in <module>
    from .load import available_model_names, available_models, get_model_description, load, load_vla
  File "/data/zhouhy/VLA-Continual-Learning/external/openvla/prismatic/models/load.py", line 16, in <module>
    from prismatic.models.materialize import get_llm_backbone_and_tokenizer, get_vision_backbone_and_transform
  File "/data/zhouhy/VLA-Continual-Learning/external/openvla/prismatic/models/materialize.py", line 12, in <module>
    from prismatic.models.backbones.llm import LLaMa2LLMBackbone, LLMBackbone, MistralLLMBackbone, PhiLLMBackbone
  File "/data/zhouhy/VLA-Continual-Learning/external/openvla/prismatic/models/backbones/llm/__init__.py", line 1, in <module>
    from .base_llm import LLMBackbone
  File "/data/zhouhy/VLA-Continual-Learning/external/openvla/prismatic/models/backbones/llm/base_llm.py", line 33, in <module>
    overwatch = initialize_overwatch(__name__)
  File "/data/zhouhy/VLA-Continual-Learning/external/openvla/prismatic/overwatch/overwatch.py", line 147, in initialize_overwatch
    return DistributedOverwatch(name) if int(os.environ.get("WORLD_SIZE", -1)) != -1 else PureOverwatch(name)
  File "/data/zhouhy/VLA-Continual-Learning/external/openvla/prismatic/overwatch/overwatch.py", line 54, in __init__
    self.logger, self.distributed_state = ContextAdapter(logging.getLogger(name), extra={}), PartialState()
  File "/data/zhouhy/Miniconda/envs/VLA_CL/lib/python3.10/site-packages/accelerate/state.py", line 211, in __init__
    torch.distributed.init_process_group(backend=self.backend, **kwargs)
  File "/data/zhouhy/Miniconda/envs/VLA_CL/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 86, in wrapper
    func_return = func(*args, **kwargs)
  File "/data/zhouhy/Miniconda/envs/VLA_CL/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1177, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/data/zhouhy/Miniconda/envs/VLA_CL/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 246, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout, use_libuv)
  File "/data/zhouhy/Miniconda/envs/VLA_CL/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 174, in _create_c10d_store
    return TCPStore(
torch.distributed.DistNetworkError: Connection reset by peer

I am wondering if anyone encountered this before or what can I try out? Thanks a lot!

**Comment by object814** [comment]
update, on my machine I run the finetuning torchrun **without** --standalone and the error went away, still waiting for the outcome but so far so good
I will just end this issue for now
