### ISSUE TITLE
Error (Expected to mark a variable ready only once) when finetuning

### ISSUE THREAD

**Issue by esychoi** [openvla/openvla#90]
I'd like to fine tune openvla-7b. As a test, I am trying to fine tune it on the utokyo_pr2_opening_fridge_converted_externally_to_rlds of Open-X Embodiment dataset.

I have customized the `finetune,py script` and this leads to an error that I don't know how to solve.
My script: https://gist.github.com/esychoi/cc1fcc55c592f282d28fca78b85099d7
The only thing I changed is the path to the model and the dataset, using quantization and commenting code regarding wandb logging.

logs:
```
(openvla-env) root@487aa4530a71:/openvla# torchrun --standalone --nnodes 1 --nproc-per-node 1 vla-scripts/finetune.py
\2024-09-05 10:54:04.444209: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-05 10:54:04.444245: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-05 10:54:04.445654: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-05 10:54:04.454453: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-05 10:54:05.683493: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
09/05 [10:54:09] INFO     | >> PyTorch version 2.2.0 available.                                                                                                                                              config.py:59
                 INFO     | >> TensorFlow version 2.15.0 available.                                                                                                                                         config.py:106
                 INFO     | >> Apache Beam version 2.58.1 available.                                                                                                                                        config.py:133
Fine-tuning OpenVLA Model `/data/models/openvla-7b` on `utokyo_pr2_opening_fridge_converted_externally_to_rlds`
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:06<00:00,  2.25s/it]
trainable params: 110,828,288 || all params: 7,652,065,472 || trainable%: 1.4483
2024-09-05 10:54:43.038700: W external/local_tsl/tsl/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "FAILED_PRECONDITION: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata.google.internal".
2024-09-05 10:54:45.613737: I tensorflow/core/grappler/optimizers/data/replicate_on_split.cc:32] Running replicate on split optimization
09/05 [10:54:46] INFO     | >> [*] Loading existing dataset statistics from                                                                                                                             data_utils.py:208
                          /data/OpenX-Embodiment/utokyo_pr2_opening_fridge_converted_externally_to_rlds/0.1.0/dataset_statistics_a439e97014ff825d571fe3388044be47dbbe100f16f8341c6f3e350f45b41a36.json.                  
2024-09-05 10:54:46.513044: I tensorflow/core/grappler/optimizers/data/replicate_on_split.cc:32] Running replicate on split optimization

######################################################################################
# Loading the following 1 datasets (incl. sampling weight):                         #
# utokyo_pr2_opening_fridge_converted_externally_to_rlds: ==================1.000000 #
######################################################################################

09/05 [10:54:47] INFO     | >> [*] Threads per Dataset: [1]                                                                                                                                                dataset.py:532
                 INFO     | >> [*] Reads per Dataset: [1]                                                                                                                                                  dataset.py:533
                 INFO     | >> [*] Constructing datasets...                                                                                                                                                dataset.py:536
2024-09-05 10:54:49.352573: I tensorflow/core/grappler/optimizers/data/replicate_on_split.cc:32] Running replicate on split optimization
09/05 [10:54:50] INFO     | >> [*] Applying frame transforms on dataset...                                                                                                                                 dataset.py:576
09/05 [10:54:52] INFO     | >> [*] Saved dataset statistics file at path                                                                                                                                data_utils.py:293
                          runs/openvla-7b+utokyo_pr2_opening_fridge_converted_externally_to_rlds+b16+lr-2e-05+lora-r32+dropout-0.0+q-4bit--image_aug/dataset_statistics.json                                             
  0%|                                                                                                                                                                                         | 0/200000 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1725533692.797889  152109 op_level_cost_estimator.cc:699] Error in PredictCost() for the op: op: "CropAndResize" attr { key: "T" value { type: DT_FLOAT } } attr { key: "extrapolation_value" value { f: 0 } } attr { key: "method" value { s: "bilinear" } } inputs { dtype: DT_FLOAT shape { dim { size: 1 } dim { size: 224 } dim { size: 224 } dim { size: -7 } } } inputs { dtype: DT_FLOAT shape { dim { size: -2 } dim { size: 4 } } } inputs { dtype: DT_INT32 shape { dim { size: -2 } } } inputs { dtype: DT_INT32 shape { dim { size: 2 } } } device { type: "CPU" vendor: "GenuineIntel" model: "111" frequency: 2198 num_cores: 40 environment { key: "cpu_instruction_set" value: "AVX SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2" } environment { key: "eigen" value: "3.4.90" } l1_cache_size: 32768 l2_cache_size: 262144 l3_cache_size: 52428800 memory_size: 268435456 } outputs { dtype: DT_FLOAT shape { dim { size: -2 } dim { size: -8 } dim { size: -9 } dim { size: -7 } } }
W0000 00:00:1725533692.798451  152109 op_level_cost_estimator.cc:699] Error in PredictCost() for the op: op: "CropAndResize" attr { key: "T" value { type: DT_FLOAT } } attr { key: "extrapolation_value" value { f: 0 } } attr { key: "method" value { s: "bilinear" } } inputs { dtype: DT_FLOAT shape { dim { size: 1 } dim { size: 224 } dim { size: 224 } dim { size: -6 } } } inputs { dtype: DT_FLOAT shape { dim { size: -3 } dim { size: 4 } } } inputs { dtype: DT_INT32 shape { dim { size: -3 } } } inputs { dtype: DT_INT32 shape { dim { size: 2 } } } device { type: "CPU" vendor: "GenuineIntel" model: "111" frequency: 2198 num_cores: 40 environment { key: "cpu_instruction_set" value: "AVX SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2" } environment { key: "eigen" value: "3.4.90" } l1_cache_size: 32768 l2_cache_size: 262144 l3_cache_size: 52428800 memory_size: 268435456 } outputs { dtype: DT_FLOAT shape { dim { size: -3 } dim { size: -10 } dim { size: -11 } dim { size: -6 } } }
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
Traceback (most recent call last):                                                                                                                                                                                       
  File "/openvla/vla-scripts/finetune.py", line 368, in <module>
    finetune()
  File "/usr/local/lib/python3.10/dist-packages/draccus/argparsing.py", line 203, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/openvla/vla-scripts/finetune.py", line 267, in finetune
    normalized_loss.backward()
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 289, in apply
    return user_fn(self, *args)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py", line 319, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 875 with name base_model.model.language_model.model.layers.31.mlp.down_proj.lora_B.default.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.
[2024-09-05 10:55:06,055] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 152109) of binary: /usr/bin/python3.10
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
vla-scripts/finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-05_10:55:06
  host      : 487aa4530a71
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 152109)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```
I have tried to set `find_unused_parameters` and `gradient_as_bucket_view` to False when loading the model with `DDP`. It gave a different error message but it still didn't work.
Thank you for your help !

**Comment by kpertsch** [comment]
Thanks for posting your solution here. If you want to dig into this more, it could be good to pick apart which change caused the error here, there are a few candidates:
- gradient accumulation
- quantization
- LoRA finetuning

Will close the issue for now!
